### ISSUE TITLE
DevOps/0_CodeStar README.md Should Be Prescriptive About Regions to Use

### ISSUE THREAD

**Issue by mcnamarabrian** [awslabs/aws-serverless-workshops#46]
The existing README.md shows that CodeStar can be launched in several regions but the CloudFormation template referenced in https://github.com/awslabs/aws-serverless-workshops/tree/master/DevOps/1_ServerlessApplicationModel#2-seed-the-uni-api-codecommit-git-repository only allows for us-east-1 and us-west-1.

The README in DevOps/0_CodeStar should state that while CodeStar is available in other regions only us-east-1 and us-west-1 should be used for the purpose of this lab.

**Comment by angelarw** [comment]
yes the CloudFormation template is only in us-east-1 and us-west-1, but it seems to take a parameter for region. so maybe that template can work with other region's CodeCommit repos?

**Comment by brotherhod** [comment]
The Cloudformation script uses a custom resource located in us-east-1 and us-west-1 that uploads the a zip format located in a region specific S3 bucket.  Given that the lambda function that supports the custom resource is set to 1024MB my guess is that it clones the code commit repo, unpacks the archive copied from the S3 mentioned in the parameters and then pushes new files to code commit.  There might be a function that does this in awslabs otherwise maybe worth creating...

**Comment by samdengler** [comment]
I've added support for the additional regions.  Please let me know if you have any issues.  Thanks for reporting the discrepancy.
